insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(11, 1,"아일랜드","롭 엘리엇","Rob Elliot","1986년 04월 30일","GK", 190, 94);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(11, 2,"아일랜드","키어런 클락","Ciaran Clark","1989년 09월 26일","DF", 188, 81);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(11, 3,"웨일스","폴 더밋","Paul Dummett","1991년 09월 26일","DF", 183, 82);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(11, 4,"대한민국","기성용","Ki Sung-Yueng","1989년 01월 24일","MF", 186, 75);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(11, 5,"스위스","파비안 셰어","Fabian Schär","1991년 12월 20일","DF", 186, 85);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(11, 6,"잉글랜드","자말 라셀스","Jamaal Lascelles","1993년 11월 11일","DF", 188, 89);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(11, 7,"잉글랜드","제이콥 머피","Jacob Murphy","1995년 02월 24일","MF", 179, 74);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(11, 8,"잉글랜드","존조 셸비","Jonjo Shelvey","1992년 02월 27일","MF", 183, 73);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(11, 9,"베네수엘라","살로몬 론돈","Salomón Rondón","1989년 09월 16일","FW", 190, 86);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(11, 10,"세네갈","모하메드 디아메","Mohamed Diamé","1987년 06월 14일","MF", 184, 86);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(11, 11,"스코틀랜드","맷 리치","Matt Ritchie","1986년 09월 10일","MF", 172, 76);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(11, 12,"슬로바키아","마르틴 두브라프카","Martin Dubravka","1989년 01월 15일","GK", 191, 80);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(11, 13,"일본","미무토 요시노리","Yoshinori Muto","1992년 07월 15일","FW", 178, 72);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(11, 14,"잉글랜드","아이삭 헤이든","Isaac Hayden","1995년 03월 22일","MF", 185, 79);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(11, 15,"브라질","케네지","Kenedy","1996년 02월 08일","FW", 182, 77);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(11, 16,"잉글랜드","롤란도 아론스","Rolando Aarons","1995년 11월 06일","MF", 178, 76);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(11, 17,"스페인","아요세 페레스","Ayoze Pérez","1993년 07월 23일","FW", 179, 68);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(11, 18,"아르헨티나","페데리코 페르난데스","Federico Fernández","1989년 02월 21일","DF", 190, 83);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(11, 19,"스페인","하비에르 만키요","Javier Manquillo","1994년 05월 05일","DF", 180, 76);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(11, 20,"프랑스","플로리앙 르죈","Florian Lejeune","1991년 05월 20일","DF", 189, 89);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(11, 21,"스페인","호셀루","Josélu","1990년 03월 27일","FW", 192, 79);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(11, 22,"미국","디안드레 예들린","DeAndre Yedlin","1993년 07월 09일","DF", 172, 75);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(11, 26,"잉글랜드","칼 달로우","Karl Darlow","1990년 10월 08일","GK", 190, 88);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(11, 30,"가나","크리스찬 아추","Christian Atsu","1992년 01월 10일","MF", 165, 65);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(11, 41,"잉글랜드","프레디 우드먼","Freddie Woodman","1997년 03월 04일","GK", 188, 83);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(11, 42,"잉글랜드","제이미 스테리","Jamie Sterry","1995년 11월 21일","DF", 175, 76);