insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(14,1,"브라질","에우렐류 다시우바 고미스","Heurelho da Silva Gomes","1981년 2월 15일","골키퍼",191,82);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(14,2,"네덜란드","다릴 얀마트","Daryl Janmaat","1989년 7월 22일","라이트백",185,82);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(14,3,"우루과이","미겔 앙헬 브리토스 카브레라","Miguel Ángel Britos Cabrera","1985년 7월 17일","센터백, 레프트백",188,82);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(14,4,"프랑스","유네스 카불","Younès Kaboul","1986년 1월 4일","센터백, 라이트백",190,87);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(14,5,"오스트리아","제바스티안 프뢰들","Sebastian Prödl","1987년 6월 21일","센터백, 수비형 미드필더",196,96);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(14,6,"자메이카","아드리안 조세프 마리아파","Adrian Joseph Mariappa","1986년 10월 3일","센터백, 라이트백",180,78);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(14,7,"스페인","제라르 데울로페우 라사로","Gerard Deulofeu Lázaro","1994년 3월 13일","윙어",177,73);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(14,8,"잉글랜드","토마스 윌리엄 톰 클레벌리","Thomas William Tom Cleverley","1989년 8월 12일","미드필더",175,63);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(14,9,"잉글랜드","트로이 매튜 디니","Troy Matthew Deeney","1988년 6월 29일","공격수",183,90);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(14,10,"나이지리아","아이작 석세스 아자이","Isaac Success Ajayi","1996년 1월 7일","공격수",182,86);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(14,14,"잉글랜드","너새니얼 니아키 찰로바","Nathaniel Nyakie Chalobah","1994년 12월 12일","중앙 미드필더, 수비형 미드필더, 센터백",185,75);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(14,15,"북아일랜드","크레이그 조지 카스카트","Craig George Cathcart","1989년 2월 6일","센터백, 라이트백",188,73);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(14,16,"프랑스","압둘라예 두쿠레","Abdoulaye Doucouré","1993년 1월 1일","미드필더",185,75);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(14,18,"잉글랜드","안드레 앤서니 그레이","Andre Anthony Gray","1991년 6월 26일","중앙 공격수, 왼쪽 윙어",178,83);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(14,19,"잉글랜드","윌리엄 제임스 휴즈","William James Hughes","1995년 4월 17일","중앙 미드필더, 수비형 미드필더, 왼쪽 미드필더",185,74);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(14,21,"스페인","프란시스코 키코 페메니아 파르","Francisco Kiko Femenía Far","1991년 2월 2일","라이트백, 오른쪽 미드필더, 오른쪽 윙어",176,61);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(14,22,"네덜란드","마르빈 로메오 크바시 제이헬라르","Marvin Romeo Kwasie Zeegelaar","1990년 8월 12일","레프트백, 왼쪽 미드필더, 왼쪽 윙어",186,84);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(14,25,"그리스","호세 로이드 홀레바스","José Lloyd Holebas","1984년 6월 27일","레프트백, 왼쪽 미드필더, 왼쪽 윙어",184,77);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(14,26,"잉글랜드","벤자민 앤서니 포스터","Benjamin Antohny Foster","1983년 4월 3일","골키퍼",193,90);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(14,27,"벨기에","크리스티앙 카바셀레","Christian Kabasele","1991년 2월 4일","센터백",188,84);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(14,29,"프랑스","에티엔 카푸","Étienne Capoue","1988년 7월 11일","수비형 미드필더, 센터백",189,75);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(14,33,"이탈리아","스테파노 추카 오카카","Stefano Chuka Okaka","1989년 8월 9일","중앙 공격수",186,82);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(14,37,"아르헨티나","로베르토 막시밀리아노 페레이라","Roberto Maximiliano Pereyra","1991년 1월 7일","공격형 미드필더, 미드필더",185,74);
