insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(16, 1,"호주","매튜 라이언","Mathew Ryan","1992년 04월 08일","GK", 181, 82);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(16, 2,"스페인","브루노 살토르","Bruno Saltor Grau","1980년 10월 01일","DF", 181, 76);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(16, 3,"카메룬","가에탕 봉","Gaëtan Bong","1988년 04월 25일","DF", 187, 74);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(16, 4,"아일랜드","셰인 더피","Shane Duffy","1992년 01월 01일","DF", 193, 76);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(16, 5,"잉글랜드","루이스 덩크","Lewis Dunk","1991년 11월 21일","DF", 192, 88);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(16, 6,"잉글랜드","데일 스티븐스","Dale Stephens","1989년 06월 12일","MF", 169, 71);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(16, 7,"이스라엘","비람 카얄","Beram Kayal","1988년 05월 02일","MF", 178, 74);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(16, 8,"말리","이브 비수마","Yves Bissouma","1996년 08월 30일","MF", 181, 80);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(16, 9,"네덜란드","위르겐 로카디아","Jurgen Locadia","1993년 11월 07일","FW", 185, 87);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(16, 11,"프랑스","앙토니 크노카에르","Anthony Knockaert","1991년 11월 20일","FW", 172, 69);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(16, 13,"독일","파스칼 그로스","Pascal Gross Groß","1991년 06월 15일","MF", 181, 76);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(16, 16,"이란","알리레자 자한바크슈","Alireza Jahanbakhsh","1993년 08월 11일","MF", 180, 78);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(16, 17,"잉글랜드","글렌 머리","Glenn Murray","1983년 09월 25일","FW", 186, 84);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(16, 19,"콜롬비아","호세 이스키에르도","José Izquierdo","1992년 07월 07일","FW", 171, 73);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(16, 20,"잉글랜드","솔리 마치","Solly March","1994년 07월 20일","MF", 180, 88);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(16, 21,"이탈리아","에제키엘 스켈로토","Ezequiel Schelotto","1989년 05월 23일","DF", 187, 77);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(16, 22,"스페인","마르틴 몬토야","Martín Montoya","1991년 04월 14일","DF", 176, 73);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(16, 24,"네덜란드","데이비 프뢰페르","Davy Pröpper","1991년 09월 02일","MF", 185, 79);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(16, 25,"이스라엘","토메르 헤메드","Tomer Hemed","1987년 05월 02일","FW", 186, 80);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(16, 29,"오스트리아","마커스 주트너","Markus Suttner","1987년 04월 16일","DF", 179, 73);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(16, 30,"브라질","키베르나르두 페르난데스","Bernardo Fernandes","1995년 05월 14일","DF", 186, 76);
