insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(20,1,"덴마크","요나스 뢰슬","Jonas Lössl","1989년 2월 1일","골키퍼",195,89);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(20,2,"잉글랜드","토마스 조지 스미스","Thomas George Smith","1992년 4월 14일","라이트백, 센터백",186,75);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(20,5,"네덜란드","테렌스 콩골로","Terence Kongolo","1994년 2월 14일","센터백, 레프트백",188,70);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(20,6,"잉글랜드","조너선 리 호그","Jonathan Lee Hogg","1988년 12월 6일","중앙 미드필더, 수비형 미드필더",170,67);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(20,8,"덴마크","필리프 애니안우 빌링","Philip Anyanwu Billing","1996년 6월 11일","중앙 미드필더, 수비형 미드필더",193,83);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(20,9,"콩고 민주 공화국","엘리아스 카충가","Elias Kachunga","1992년 4월 22일","중앙 공격수, 윙어",178,74);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(20,10,"호주","애런 무이","Aarom Mooy","1990년 9월 15일","미드필더",173,75);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(20,12,"잉글랜드","벤자민 존 하머","Benjamin John Hamer","1987년 11월 20일","골키퍼",192,91);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(20,14,"이집트","라마단 소브히","Ramadan Sobhi","1997년 1월 23일","윙어, 공격형 미드필더",183,72);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(20,15,"독일","크리스 예르크 뢰베","Chris Jorg Löwe","1989년 4월 16일","레프트백, 왼쪽 미드필더",175,68);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(20,17,"네덜란드","라지브 라몬 판라파라","Rajiv Ramon van La Parra","1991년 6월 4일","윙어",181,72);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(20,19,"미국","다니엘 윌리엄스","Daniel Williams","1989년 3월 8일","수비형 미드필더, 라이트백, 오른쪽 미드필더",182,79);	
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(20,20,"벨기에","로랑 드푸아트르","Laurent Depoitre","1988년 12월 7일","중앙 공격수",191,91);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(20,21,"잉글랜드","알렉스 데이비드 프리차드","Alex David Pritchard","1993년 5월 3일","윙어, 공격형 미드필더",171,62);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(20,23,"독일","콜린 콰너","Collin Quaner","1991년 6월 18일","중앙 공격수, 윙어",191,81);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(20,24,"베냉","스티브 무니에","Steve Mounié","1994년 9월 29일","중앙 공격수",190,83);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(20,25,"덴마크","마티아스 야타니에 예르겐센","Mathias Jattah-Njie Jørgensen","1990년 4월 23일","센터백",191,79);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(20,26,"독일","크리스토퍼 볼프강 게오르그 아우구스트 쉰들러","Christopher Wolfgang Georg August Schindler","1990년 4월 29일","센터백,풀백",189,77);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(20,27,"슬로베니아","욘 고렌츠 스탄코비치","Jon Gorenc Stanković","1996년 1월 14일","센터백, 수비형 미드필더",190,78);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(20,11,"모로코","압델하미드 사비리","Abdelhamid Sabiri","1996년 11월 28일","공격형 미드필더, 중앙 미드필더, 왼쪽 미드필더",183,80);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(20,31,"잉글랜드","라이언 스코필드","Ryan Schofield","1999년 12월 11일","골키퍼",190,70);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(20,33,"스위스,알바니아,코소보","플로렌트 하데조나이","Florent Hadergjonaj","1994년 7월 31일","라이트백, 오른쪽 미드필더, 수비형 미드필더",182,73);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(20,37,"독일","에리크 두름","Erik Durm","1992년 5월 12일","풀백",180,72);
