insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(5,1,"칠레","클라우디오 브라보","Claudio Bravo","1983년 04월 13일","GK", 184, 80);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(5,2,"잉글랜드","카일 워커","Kyle Walker","1990년 05월 28일","DF", 183, 70);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(5,3,"브라질","다닐루 루이스","Danilo Luiz","1991년 07월 15일","DF", 184, 78);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(5,4,"벨기에","뱅상 콩파니","Vincent Kompany","1986년 04월 10일","DF", 190, 85);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(5,5,"잉글랜드","존 스톤스","John Stones","1994년 05월 28일","DF", 188, 70);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(5,7,"잉글랜드","라힘 스털링","Raheem Sterling","1994년 12월 08일","MF", 170, 69);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(5,8,"독일","일카이 귄도안","Ilkay Gündoğan","1990년 10월 24일","MF", 180, 80);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(5,10,"아르헨티나","세르히오 아궤로","Sergio 'Kun' Agüero","1988년 06월 02일","FW", 173, 70);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(5,14,"프랑스","에이므리크 라포르트","Aymeric Laporte","1994년 05월 27일","DF", 191, 85);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(5,15,"프랑스","엘리아킴 망갈라","Eliaquim Mangala","1991년 02월 13일","DF", 188, 84);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(5,17,"프랑스","케빈 더 브라위너","Kevin De Bruyne","1991년 06월 28일","MF", 181, 68);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(5,18,"잉글랜드","페이비언 델프","Fabian Delph","1989년 11월 21일","DF", 174, 60);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(5,19,"독일","리로이 자네","Leroy Sané","1996년 01월 11일","MF", 183, 75);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(5,20,"포르투갈","베르나르두 실바","Bernardo Silva","1994년 08월 10일","MF", 173, 64);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(5,21,"스페인","다비드 실바","David Silva","1986년 01월 08일","MF", 173, 67);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(5,22,"프랑스","뱅자맹 망디","Benjamin Mendy","1994년 07월 17일","DF", 185, 85);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(5,25,"브라질","페르난지뉴 루이스","Fernandinho Luiz","1985년 05월 04일", "MF", 179, 67);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(5,26,"알제리","리야드 마레즈","Riyad Mahrez","1991년 02월 21일","MF", 179, 67);
insert into player(team_no, back_no,country,name_kr,name_en,birthday,position,height,weight) values(5,30,"아르헨티나","니콜라스 오타멘디","Nicolás Otamendi","1988년 02월 12일","DF", 183, 81);
insert into player(team_no, back_no,country,position,name_kr,name_en,birthday,height,weight) values(5,31,"브라질","GK","에데르송 모라에스","Ederson Moraes","1993년 08월 17일", 188, 86);
insert into player(team_no, back_no,country,position,name_kr,name_en,birthday,height,weight) values(5,32,"잉글랜드","GK","다니엘 그림쇼","Daniel Grimshaw","1998년 01월 16일", 185, 77);
insert into player(team_no, back_no,country,position,name_kr,name_en,birthday,height,weight) values(5,33,"브라질","FW","가브리엘 제주스"," Gabriel Jesus ","1997년 04월 03일", 175, 73);
insert into player(team_no, back_no,country,position,name_kr,name_en,birthday,height,weight) values(5,34,"네덜란드","DF","필립 산들러르","Philippe Sandler","1997년 02월 10일", 188, 82);
insert into player(team_no, back_no,country,position,name_kr,name_en,birthday,height,weight) values(5,35,"우크라이나","MF","올렉산드르 진첸코","Oleksandr Zinchenko","1996년 12월 15일", 175, 64);
insert into player(team_no, back_no,country,position,name_kr,name_en,birthday,height,weight) values(5,47,"잉글랜드","MF","필 포든","Phil Foden","2000년 05월 28일", 171, 59);
insert into player(team_no, back_no,country,position,name_kr,name_en,birthday,height,weight) values(5,49,"코소보","GK","아로 무리치","Aro Murić","1998년 11월 07일", 199, 81);
insert into player(team_no, back_no,country,position,name_kr,name_en,birthday,height,weight) values(5,55,"스페인","MF","브라힘 디아스"," Brahim Díaz","1999년 08월 03일", 170, 68);
