insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(7,1,"잉글랜드","조던 리 픽퍼드","Jordan Lee Pickford","1994년 3월 7일","골키퍼",185,77);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(7,2,"잉글랜드","메이슨 앤서니 홀게이트","Mason Anthony Holgate","1996년 10월 22일","센터백,풀백",184,70);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(7,3,"잉글랜드","레이턴 존 베인스","Leighton John Baines","1984년 12월 11일","레프트백",170,74);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(7,4,"잉글랜드","마이클 빈센트 킨","Michael Vincent Keane","1993년 1월 11일","센터백",191,82);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(7,5,"프랑스","퀴르트 아피 주마","Kurt Happy Zouma","1994년 10월 27일","센터백, 라이트백",190,96);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(7,6,"잉글랜드","필립 니코뎀 필 자기엘카","Philip Nikodem Phil Jagielka","1982년 8월 17일","중앙 수비수, 수비형 미드필더, 골키퍼",183,83);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(7,8,"포르투갈","안드레 필리프 타바르스 고메스","André Filipe Tavares Gomes","1993년 7월 30일","중앙 미드필더",188,84);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(7,10,"아이슬란드","길비 소르 시귀르드손","Gylfi Þór Sigurðsson","1989년 9월 8일","공격형 미드필더, 윙어",186,79);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(7,11,"잉글랜드","시오 제임스 월컷","Theo James Walcott","1989년 3월 16일","윙어, 스트라이커",176,68);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(7,12,"프랑스","뤼카 디뉴","Lucas Digne","1993년 7월 20일","레프트백",178,74);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(7,13,"콜롬비아","예리 페르난도 미나 곤살레스","Yerry Fernando Mina González","1994년 9월 23일","센터백",195,94);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(7,14,"터키","젠크 토순","Cenk Tosun","1991년 6월 7일","중앙 공격수",184,78);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(7,16,"아일랜드","제임스 매카시","James McCarthy","1990년 11월 12일","중앙 미드필더",180,72);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(7,17,"세네갈","이드리사 가나 게예","Idrissa Gana Gueye","1989년 9월 26일","수비형 미드필더",174,74);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(7,18,"프랑스","모르강 슈네데를랭","Morgan Schneiderlin","1989년 11월 8일","수비형 미드필더, 중앙 미드필더",185,75);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(7,19,"세네갈","우마르 니아세","Oumar Niasse","1990년 4월 13일","공격수",182,75);	
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(7,20,"브라질","베르나르드 아니시우 카우데이라 두아르치","Bernard Anício Caldeira Duarte","1992년 9월 8일","윙어",164,60);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(7,22,"네덜란드","마르턴 스테켈렌뷔르흐","Maarten Stekelenburg","1982년 9월 22일","골키퍼",197,92);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(7,23,"아일랜드","셰이머스 콜먼","Séamus Coleman","1988년 10월 11일","라이트백, 윙어",177,67);	
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(7,26,"잉글랜드","토마스 톰 데이비스","Thomas Tom Davies","1998년 6월 30일","중앙 미드필더",180,70);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(7,28,"잉글랜드","키에런 오닐 도웰","Kieran O'Neill Dowell","1997년 10월 10일","미드필더",178,59);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(7,30,"브라질","히샤를리종 지안드라지","Richarlison de Andrade","1997년 5월 10일","왼쪽 윙어",179,71);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(7,31,"잉글랜드","아데몰라 루크먼 올라야데 알라데 아일롤라 루크먼","Ademola Lookman Olajade Alade Aylola Lookman","1997년 10월 20일","윙어",174,78);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(7,34,"잉글랜드","베니 탄가마 베닌지메","Beni Tangama Baningime","1998년 9월 9일","중앙 미드필더",178,70);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(7,43,"잉글랜드","존조 케니","Jonjoe Kenny","1997년 3월 15일","라이트백",176,67);
