insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(17,1,"필리핀,잉글랜드","닐 레오나르드 둘라 에서릿지","Neil Leonard Dula Etheridge","1990년 2월 7일","골키퍼",191,89);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(17,2,"잉글랜드","리 앤서니 펠티어","Lee Anthony Peltier","1986년 12월 11일","센터백, 라이트백",180,73);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(17,3,"잉글랜드","조셉 베넷","Joseph Bennett","1990년 3월 28일","레프트백",178,74);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(17,4,"잉글랜드","션 조셉 모리슨","Sean Joseph Morrison","1991년 1월 8일","센터백",193,84);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(17,5,"가봉","브루노 에퀼레 망가","Bruno Ecuele Manga","1988년 7월 16일","센터백",186,76);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(17,6,"웨일스","애슐리 대럴 재즈 리차즈","Ashley Darel Jazz Richards","1991년 4월 12일","풀백,미드필더",185,78);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(17,7,"아일랜드,잉글랜드","해리 니콜라스 아터","Harry Nicholas Arter","1989년 12월 28일","중앙 미드필더,수비형 미드필더",176,70);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(17,8,"잉글랜드","조셉 윌리엄 롤스","Joseph William Ralls","1993년 10월 13일","미드필더",178,70);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(17,9,"잉글랜드","대니얼 칼 워드","Daniel Carl Ward","1991년 12월 11일","공격수",180,88);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(17,10,"덴마크","케네스 조호르","Kenneth Zohore","1993년 10월 13일","공격수",192,98);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(17,11,"잉글랜드","조슈아 머피","Joshua Murphy","1995년 2월 24일","윙어",173,67);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(17,12,"잉글랜드","알렉산더 스미시즈","Alexander Smithies","1990년 3월 5일","골키퍼",188,84);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(17,13,"스코틀랜드","칼럼 토마스 오언 패터슨","Callum Thomas Owen Paterson","1994년 10월 13일","수비수",183,76);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(17,16,"잉글랜드","매튜 토마스 마틴 코널리","Matthew Thomas Martin Connolly","1987년 9월 24일","수비수",188,84);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(17,17,"아이슬란드","아론 에이나르 말름퀴스트 군나르손","Aron Einar Malmquist Gunnarsson","1989년 4월 22일","중앙 미드필더",178,95);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(17,22,"코트디부아르","솔 밤바","Souleymane Sol Bamba","1985년 1월 13일","센터백",190,86);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(17,33,"캐나다","주니어 호일렛","David Wayne Junior Hoilett","1988년 6월 6일","윙어",173,70);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(17,26,"아일랜드","앤서니 필킹턴","Anthony Pilkington","1988년 6월 6일","윙어",183,81);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(17,25,"잉글랜드","리 마크 톰린","Lee Marc Tomlin","1989년 1월 12일","스트라이커, 공격형 미드필더",180,74);
