insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(9,1,"덴마크","카스페르 페테르 슈마이켈","Kasper Peter Schmeichel","1986년 11월 5일","골키퍼",187,89);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(9,2,"잉글랜드","대니얼 피터 '대니' 심슨","Daniel Peter 'Danny' Simpson","1987년 1월 4일","라이트백",177,78);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(9,3,"잉글랜드","벤자민 제임스 칠웰","Benjamin James Chilwell","1996년 12월 21일","레프트백",178,71);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(9,4,"잉글랜드","찰라르 쇠윈쥐","Çağlar Söyüncü","1996년 5월 23일","센터백",187,82);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(9,5,"자메이카","웨슬리 네이선 웨스 모건","Westley Nathan Wes Morgan","1984년 1월 21일","센터백",185,101);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(9,6,"북아일랜드","조너선 그랜트 조니 에번스","Jonathan Grant Jonny Evans","1988년 1월 3일","센터백, 레프트백",188,78);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(9,7,"잉글랜드","데머레이 그레이","Demarai Gray","1996년 6월 28일","왼쪽 윙어, 오른쪽 윙어, 공격형 미드필더",179,66);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(9,8,"나이지리아","켈레치 프로미스 이헤아나초","Kelechi Promise Iheanacho","1996년 10월 3일","스트라이커",186,82);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(9,9,"잉글랜드","제이미 리처드 바디","Jamie Richard Vardy","1987년 1월 11일","스트라이커, 윙어",175,74);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(9,10,"잉글랜드","제임스 매디슨","James Maddison","1996년 11월 23일","공격형 미드필더, 윙어",175,73);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(9,11,"잉글랜드","마크 케빈 올브라이턴","Marc Kevin Albrighton","1989년 11월 18일","미드필더",175,67);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(9,12,"웨일스","다니엘 대니 워드","Daniel Danny Ward","1993년 6월 22일","골키퍼",193,88);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(9,14,"포르투갈","히카르두 도밍구스 바르보자 페레이라","Ricardo Domingos Barbosa Pereira","1993년 10월 6일","라이트백",175,70);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(9,15,"잉글랜드","해리 매과이어","Harry Maguire","1993년 3월 5일","센터백",194,100);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(9,17,"스위스","엘딘 야쿠포비치","Eldin Jakupović","1984년 10월 2일","골키퍼",191,85);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(9,18,"가나 공화국","다니엘 아마티","Daniel Amartey","1994년 12월 21일","수비형 미드필더, 센터백, 라이트백",183,78);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(9,31,"알제리","이슬람 슬리마니","Islam Slimani","1988년 6월 18일","스트라이커",188,79);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(9,20,"일본","오카자키 신지","Shinji Okazaki","1986년 4월 16일","스트라이커, 윙어",174,70);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(9,21,"스페인","비센테 이보라 데라푸엔테","Vicente Iborra de la Fuente","1988년 1월 16일","수비형 미드필더",190,91);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(9,22,"잉글랜드","매티 제임스","Matthew Lee James","1991년 7월 21일","중앙미드필더",181,86);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(9,23,"포르투갈","아드리앵 세바스티앵 페루셰 다실바","Adrien Sébastien Perruchet da Silva","1989년 3월 15일","미드필더",175,69);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(9,24,"프랑스","낭팔리 망디","Nampalys Mendy","1992년 6월 23일","수비형 미드필더",168,68);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(9,25,"나이지리아","윌프레드 은디디","Wilfred Ndidi","1996년 12월 16일","수비형 미드필더",187,80);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(9,27,"말리,프랑스","푸세니 디아바테","Fousseni Diabaté","1995년 10월 18일","중앙 공격수,윙어",175,60);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(9,28,"오스트리아","크리스티안 푹스","Christian Fuchs","1986년 4월 7일","레프트백, 미드필더",186,80);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(9,29,"튀니지","요한 벤알루안","Yohan Ben alouane","1987년 3월 28일","센터백, 풀백",185,86);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(9,31,"알제리","라시드 게잘","Rachid Ghezzal","1992년 5월 9일","미드필더",182,65);
insert into player(team_no,back_no,country,name_kr,name_en,birthday,position,height,weight) values(9,37,"웨일스","앤드루 필립 앤디 킹","Andrew Philip Andy King","1988년 10월 29일","수비형 미드필더, 공격형 미드필더",183,75);

