insert into team(team_name_en, team_name_kr, manager_en, manager_kr, stadium, win_no) values("Manchester United FC", "맨체스터 유나이티드 FC", "José Mourinho", "주제 무리뉴", "올드 트래포드(Old Trafford)", 20);
insert into team(team_name_en, team_name_kr, manager_en, manager_kr, stadium, win_no) values("Chelsea F.C.", "첼시 FC", "Maurizio Sarri", "마우리치오 사리", "스탬퍼드 브리지 (Stamford Bridge)", 6);
insert into team(team_name_en, team_name_kr, manager_en, manager_kr, stadium, win_no) values("Liverpool FC", "리버풀 FC", "Jürgen Klopp", "위르겐 클롭", "안필드 (Anfield)", 18);
insert into team(team_name_en, team_name_kr, manager_en, manager_kr, stadium, win_no) values("Arsenal FC", "아스널 FC", "Unai Emery", "우나이 에메리", "에미레이트 스타디움 (Emirates Stadium)", 13);
insert into team(team_name_en, team_name_kr, manager_en, manager_kr, stadium, win_no) values("Manchester City FC", "맨체스터 시티 FC", "Josep Guardiola", "펩 과르디올라", "에티하드 스타디움 (Etihad Stadium)", 5);
insert into team(team_name_en, team_name_kr, manager_en, manager_kr, stadium, win_no) values("Tottenham Hotspur FC", "토트넘 핫스퍼 FC", "Mauricio Pochettino", "마우리시오 포체티노", "웸블리 스타디움 (Wembley Stadium)", 2);
insert into team(team_name_en, team_name_kr, manager_en, manager_kr, stadium, win_no) values("Everton FC", "에버턴 FC", "Marco Silva", "마르코 실바", "구디슨 파크 (Goodison Park)", 9);
insert into team(team_name_en, team_name_kr, manager_en, manager_kr, stadium, win_no) values("Fulham F.C.","풀럼 FC","Claudio Ranieri","클라우디오 라니에리","크레이븐 코티지 (Craven Cottage) ",0);
insert into team(team_name_en, team_name_kr, manager_en, manager_kr, stadium, win_no) values("Leicester City FC", "레스터 시티 FC", "Claude Puel", "클로드 퓌엘", "킹 파워 스타디움 (King Power Stadium)", 1);
insert into team(team_name_en, team_name_kr, manager_en, manager_kr, stadium, win_no) values("Wolverhampton Wanderers FC", "울버햄튼 원더러스 FC", "Nuno Espírito Santo", "누누 산투","몰리뉴 스타디움", 3);
insert into team(team_name_en, team_name_kr, manager_en, manager_kr, stadium, win_no) values("Newcastle United FC", "뉴캐슬 유나이티드 FC", "Rafael Benítez", "라파엘 베니테스","세인트 제임스 파크", 4);
insert into team(team_name_en, team_name_kr, manager_en, manager_kr, stadium, win_no) values("West Ham United FC", "웨스트햄 유나이티드 FC", "Manuel Pellegrini", "마누엘 펠레그리니","런던 스타디움", 0);
insert into team(team_name_en, team_name_kr, manager_en, manager_kr, stadium, win_no) values("Crystal Palace FC", "크리스탈 팰리스 FC", "Roy Hodgson", "로이 호지슨", "셀허스트 파크", 0);
insert into team(team_name_en, team_name_kr, manager_en, manager_kr, stadium, win_no) values("Watford FC", "왓포드 FC", "Javi Gracia", "하비 그라시아", "비커리지 로드 (Vicarage Road)", 0);
insert into team(team_name_en, team_name_kr, manager_en, manager_kr, stadium, win_no) values("Burnley FC", "번리 FC", "Sean Dyche", "션 다이치", "터프 무어", 2);
insert into team(team_name_en, team_name_kr, manager_en, manager_kr, stadium, win_no) values("Brighton & Hove Albion FC", "브라이튼 앤 호브 알비온 FC", "Chris Hughton", "크리스 휴튼", "아메리칸 익스프레스 커뮤니티 스타디움", 0);
insert into team(team_name_en, team_name_kr, manager_en, manager_kr, stadium, win_no) values("Cardiff City F.C.","카디프 시티 FC","Neil Warnock","닐 워녹","카디프 시티 스타디움 (Cardiff City Stadium)",0);
insert into team(team_name_en, team_name_kr, manager_en, manager_kr, stadium, win_no) values("Southampton F.C.","사우샘프턴 FC","Mark Hughes","마크 휴즈","세인트 메리즈 스타디움 (St. Mary's Stadium)",0);
insert into team(team_name_en, team_name_kr, manager_en, manager_kr, stadium, win_no) values("AFC Bournemouth", "AFC 본머스", "Eddie Howe", "에디 하우", "바이탈리티 스타디움 (Vitality Stadium)", 0);
insert into team(team_name_en, team_name_kr, manager_en, manager_kr, stadium, win_no) values("Huddersfield Town A.F.C.","허더즈필드 타운 AFC","David Wagner","다비트 바그너","존 스미스 스타디움 (John Smith's Stadium)",3);
